window.AGENT_WORKS_CASES = [
  {
    id: "wordpress-daily-publish",
    title: "WordPressに日課記事を3本公開する",
    agent: "Codex",
    category: "WordPress",
    purpose: "反応ログとPDCAを見て、今日書くべき記事を選び、WordPressへ公開する。",
    result: "記事タイトル、本文、メタ情報、カテゴリ、内部リンクを整えた公開作業まで進められた。",
    input: "運用ログ、過去記事、反応ログ、収益導線、投稿先WordPressの接続情報。",
    humanCheck: "公開前後の方向性、最終的な訴求、画像の良し悪しは人間が確認すると安心。",
    fit: "日々ブログを更新したい個人事業者、AI記事運用を商品導線へつなげたい人。",
    caution: "ログイン状態やアプリケーションパスワードが切れていると、接続確認が必要。",
    link: "https://acs-developer.com/",
    linkLabel: "ACS Developer",
    tags: ["記事公開", "SEO", "日課運用"]
  },
  {
    id: "wordpress-image-insert",
    title: "生成済み画像をWordPress記事へ挿入する",
    agent: "Codex",
    category: "WordPress",
    purpose: "複数記事に対して、アイキャッチと本文挿絵を対応順に挿入する。",
    result: "添付画像を記事ごとに割り当て、アイキャッチと本文内画像として登録できた。",
    input: "記事URLまたは投稿ID、画像ファイル、画像の並び順、どの記事へ何枚入れるかの指定。",
    humanCheck: "画像内テキストの誤字、訴求文のズレ、記事と画像の対応は人間確認が必要。",
    fit: "AI画像を使ってブログ記事の見た目を整えたい運営者。",
    caution: "画像の文字崩れがある場合、記事側では直せないので画像再生成が必要。",
    link: "https://acs-developer.com/",
    linkLabel: "WordPress運用支援を見る",
    tags: ["画像挿入", "アイキャッチ", "記事装飾"]
  },
  {
    id: "obsidian-secretary-review",
    title: "Obsidianを読んで朝レビューと夜まとめを作る",
    agent: "Codex",
    category: "Obsidian",
    purpose: "デイリーノート、週次目標、反応ログ、各事業ノートから今日やることを整理する。",
    result: "未完了、優先順位、収益化に近い行動、明日の最優先をひとつの流れにまとめられた。",
    input: "Obsidian Vault、デイリーノート、運用ルール、事業別ログ。",
    humanCheck: "その日の体力、外出予定、実際の気分は人間側で補足すると精度が上がる。",
    fit: "AI秘書を作りたい人、毎日の作業を資産化したい人。",
    caution: "保存先ルールが曖昧だと、AIが参照先を探す時間が増える。",
    link: "https://note.com/locany",
    linkLabel: "運用noteを見る",
    tags: ["AI秘書", "日次運用", "Vault"]
  },
  {
    id: "note-publish-blog",
    title: "noteの下書きを公開設定まで進める",
    agent: "Codex",
    category: "note",
    purpose: "Obsidian内の下書きをnoteへ投入し、タグ、マガジン、公開設定を整える。",
    result: "本文投入、無料記事設定、タグ追加、マガジン追加、公開後URL確認まで進められた。",
    input: "note下書き、投稿先アカウント、タグ、マガジン、公開設定方針。",
    humanCheck: "有料/無料、タイトルの温度、販売導線、公開前の違和感は人間が確認する。",
    fit: "noteを定期的に公開したい人、運用ログを発信資産にしたい人。",
    caution: "noteのUI変更やログイン状態によって、Chrome操作の確認が必要になる。",
    link: "https://note.com/locany",
    linkLabel: "Locany note",
    tags: ["note公開", "マガジン", "発信"]
  },
  {
    id: "diginote-ai-update",
    title: "AIニュースを選び、DiginoteAIの記事にする",
    agent: "Codex",
    category: "リサーチ",
    purpose: "AI企業リサーチから、収益化や実務活用に近いニュースを選んで記事化する。",
    result: "一次情報を読み、既存記事との重複を避けて、DiginoteAI向けの記事を追加できた。",
    input: "AIニュースリサーチ、既存記事一覧、サイトのトンマナ、更新ログ。",
    humanCheck: "どのニュースを事業導線へ寄せるか、深掘りする価値があるかは人間判断が効く。",
    fit: "AIニュースサイトを運営したい人、日々のリサーチを記事資産にしたい人。",
    caution: "公式情報の確認と重複チェックを省くと、薄いニュース要約になりやすい。",
    link: "https://diginoteai.com/",
    linkLabel: "DiginoteAI",
    tags: ["AIニュース", "記事化", "一次情報"]
  },
  {
    id: "threads-draft-stock",
    title: "日々の作業ログからThreads投稿案を作る",
    agent: "Codex",
    category: "SNS",
    purpose: "会話や作業ログから、手動リライト用のThreads投稿案をストックする。",
    result: "予約投稿ではなく、ユーザーが自分で直して投稿できる一次情報ベースの案を蓄積できた。",
    input: "当日のデイリー、反応ログ、DiginoteAI更新、作業中の気づき。",
    humanCheck: "最終的な言い回し、絵文字、投稿タイミングは本人が決めると伸びる型を学習しやすい。",
    fit: "SNSをAI任せにしすぎず、自分のトーンを育てたい人。",
    caution: "AIの完成文をそのまま出すより、本人の熱量を足した方が反応を取りやすい。",
    link: "https://note.com/locany",
    linkLabel: "発信運用の考え方を見る",
    tags: ["Threads", "投稿案", "トンマナ"]
  },
  {
    id: "search-console-check",
    title: "Search Consoleの詰まりを確認する",
    agent: "Codex",
    category: "分析",
    purpose: "サイトマップ、URL検査、検索パフォーマンスを見て、次の一手を決める。",
    result: "サイト側の公開状態とSearch Console側の認識待ちを分けて判断できた。",
    input: "対象サイトURL、Search Console画面、サイトマップURL、公開済み記事。",
    humanCheck: "インデックス登録リクエストの上限や重要ページの優先順位は人間と相談するとよい。",
    fit: "公開した記事が検索に見つからない原因を切り分けたい人。",
    caution: "すぐに検索流入が出ない時でも、サイト側の問題とは限らない。",
    link: "https://ai-workroom-catalog.pages.dev/",
    linkLabel: "実験サイトを見る",
    tags: ["Search Console", "SEO", "サイトマップ"]
  },
  {
    id: "theme-route-improvement",
    title: "WordPressテーマに記事回遊導線を追加する",
    agent: "Codex",
    category: "Web制作",
    purpose: "TOPページから記事一覧、カテゴリ、新着記事へ自然に進める導線を作る。",
    result: "テーマ側で新着記事やカテゴリ導線を表示できる設計に変更できた。",
    input: "テーマファイル、現在のTOPページ、記事カテゴリ、表示/非表示の要件。",
    humanCheck: "どのカテゴリを見せるか、売りたいサービスへどう流すかは運営方針に合わせる。",
    fit: "WordPressサイトの回遊率を上げたい人、記事から商品導線へつなげたい人。",
    caution: "テーマ更新後は、実サイトへZIPアップロードして表示確認が必要。",
    link: "https://acs-developer.com/",
    linkLabel: "サイト改善相談",
    tags: ["テーマ改修", "回遊", "内部リンク"]
  },
  {
    id: "youtube-script-slides",
    title: "YouTube台本とスライド構成を作る",
    agent: "Codex",
    category: "YouTube",
    purpose: "noteやサイト運用の内容を、YouTube動画の構成と台本に変換する。",
    result: "動画の導入、章立て、話す内容、画面に出すスライド案まで整理できた。",
    input: "元記事、訴求したい商品、動画の目的、想定視聴者。",
    humanCheck: "話すテンポ、尺、声に出した時の自然さは収録前に人間が調整するとよい。",
    fit: "記事やnoteを動画導線へ展開したい人。",
    caution: "想定尺に対して台本が短くなりやすいので、収録尺ベースで確認する。",
    link: "https://www.youtube.com/",
    linkLabel: "YouTubeで活用",
    tags: ["台本", "スライド", "動画導線"]
  },
  {
    id: "cloudflare-static-mvp",
    title: "Cloudflare Pages向けの静的MVPを作る",
    agent: "Codex",
    category: "Web制作",
    purpose: "サーバーを持たず、無料枠で公開できる静的サイトを作る。",
    result: "HTML/CSS/JavaScriptだけで、検索・カテゴリ・詳細表示のあるMVPを作成できた。",
    input: "サイト名、コンセプト、掲載したい初期データ、将来の拡張方針。",
    humanCheck: "ドメイン接続、Cloudflare Pagesのプロジェクト作成、公開前のブランド確認は人間が行う。",
    fit: "まず軽く検証したい新規サイト、サテライトサイト、事例集。",
    caution: "会員登録や投稿機能を付ける場合は、後からSupabaseなどのDBが必要になる。",
    link: "https://pages.cloudflare.com/",
    linkLabel: "Cloudflare Pages",
    tags: ["静的サイト", "MVP", "Cloudflare"]
  },
  {
    id: "ai-agent-workroom-glass-ui",
    title: "AI Agent Workroomの近未来Glass UIを公開する",
    agent: "Codex",
    category: "Web制作",
    purpose: "AIでできたことを見せる事例サイトを、見た目そのものでも制作実績になる品質へ引き上げる。",
    result: "白い近未来オフィス風の背景、ガラスカード、スクロール連動ヒーロー、左右から集まるセクション演出まで実装してCloudflare Pagesへ公開できた。",
    input: "サイトの目的、参考画像、既存の静的サイト一式、GitHubとCloudflare Pagesの公開環境。",
    humanCheck: "ブランドの温度感、派手さの許容ライン、販売導線へつなげる文言は人間が判断するとよい。",
    fit: "AIで作ったサイトを単なる試作品ではなく、制作依頼につながるポートフォリオにしたい人。",
    caution: "リッチ演出はスマホ表示と読み込み速度を確認しながら入れる必要がある。",
    link: "https://acs-developer.com/",
    linkLabel: "サイト制作相談を見る",
    tags: ["Glass UI", "Cloudflare", "制作実績"]
  }
];
