window.AGENT_WORKS_CASES = [
  {
    id: "wordpress-daily-publish",
    title: "WordPressに日課記事を3本公開する",
    agent: "Codex",
    category: "WordPress",
    purpose: "反応ログとPDCAを見て、今日書くべき記事を選び、WordPressへ公開する。",
    result: "記事タイトル、本文、メタ情報、カテゴリ、内部リンクを整えた公開作業まで進められた。",
    input: "運用ログ、過去記事、反応ログ、収益導線、投稿先WordPressの接続情報。",
    humanCheck: "公開前後の方向性、最終的な訴求、画像の良し悪しは人間が確認すると安心。",
    fit: "日々ブログを更新したい個人事業者、AI記事運用を商品導線へつなげたい人。",
    caution: "ログイン状態やアプリケーションパスワードが切れていると、接続確認が必要。",
    link: "https://acs-developer.com/",
    linkLabel: "ACS Developer",
    tags: ["記事公開", "SEO", "日課運用"]
  },
  {
    id: "wordpress-image-insert",
    title: "生成済み画像をWordPress記事へ挿入する",
    agent: "Codex",
    category: "WordPress",
    purpose: "複数記事に対して、アイキャッチと本文挿絵を対応順に挿入する。",
    result: "添付画像を記事ごとに割り当て、アイキャッチと本文内画像として登録できた。",
    input: "記事URLまたは投稿ID、画像ファイル、画像の並び順、どの記事へ何枚入れるかの指定。",
    humanCheck: "画像内テキストの誤字、訴求文のズレ、記事と画像の対応は人間確認が必要。",
    fit: "AI画像を使ってブログ記事の見た目を整えたい運営者。",
    caution: "画像の文字崩れがある場合、記事側では直せないので画像再生成が必要。",
    link: "https://acs-developer.com/",
    linkLabel: "WordPress運用支援を見る",
    tags: ["画像挿入", "アイキャッチ", "記事装飾"]
  },
  {
    id: "obsidian-secretary-review",
    title: "Obsidianを読んで朝レビューと夜まとめを作る",
    agent: "Codex",
    category: "Obsidian",
    purpose: "デイリーノート、週次目標、反応ログ、各事業ノートから今日やることを整理する。",
    result: "未完了、優先順位、収益化に近い行動、明日の最優先をひとつの流れにまとめられた。",
    input: "Obsidian Vault、デイリーノート、運用ルール、事業別ログ。",
    humanCheck: "その日の体力、外出予定、実際の気分は人間側で補足すると精度が上がる。",
    fit: "AI秘書を作りたい人、毎日の作業を資産化したい人。",
    caution: "保存先ルールが曖昧だと、AIが参照先を探す時間が増える。",
    link: "https://note.com/locany",
    linkLabel: "運用noteを見る",
    tags: ["AI秘書", "日次運用", "Vault"]
  },
  {
    id: "note-publish-blog",
    title: "noteの下書きを公開設定まで進める",
    agent: "Codex",
    category: "note",
    purpose: "Obsidian内の下書きをnoteへ投入し、タグ、マガジン、公開設定を整える。",
    result: "本文投入、無料記事設定、タグ追加、マガジン追加、公開後URL確認まで進められた。",
    input: "note下書き、投稿先アカウント、タグ、マガジン、公開設定方針。",
    humanCheck: "有料/無料、タイトルの温度、販売導線、公開前の違和感は人間が確認する。",
    fit: "noteを定期的に公開したい人、運用ログを発信資産にしたい人。",
    caution: "noteのUI変更やログイン状態によって、Chrome操作の確認が必要になる。",
    link: "https://note.com/locany",
    linkLabel: "Locany note",
    tags: ["note公開", "マガジン", "発信"]
  },
  {
    id: "diginote-ai-update",
    title: "AIニュースを選び、DiginoteAIの記事にする",
    agent: "Codex",
    category: "リサーチ",
    purpose: "AI企業リサーチから、収益化や実務活用に近いニュースを選んで記事化する。",
    result: "一次情報を読み、既存記事との重複を避けて、DiginoteAI向けの記事を追加できた。",
    input: "AIニュースリサーチ、既存記事一覧、サイトのトンマナ、更新ログ。",
    humanCheck: "どのニュースを事業導線へ寄せるか、深掘りする価値があるかは人間判断が効く。",
    fit: "AIニュースサイトを運営したい人、日々のリサーチを記事資産にしたい人。",
    caution: "公式情報の確認と重複チェックを省くと、薄いニュース要約になりやすい。",
    link: "https://diginoteai.com/",
    linkLabel: "DiginoteAI",
    tags: ["AIニュース", "記事化", "一次情報"]
  },
  {
    id: "threads-draft-stock",
    title: "日々の作業ログからThreads投稿案を作る",
    agent: "Codex",
    category: "SNS",
    purpose: "会話や作業ログから、手動リライト用のThreads投稿案をストックする。",
    result: "予約投稿ではなく、ユーザーが自分で直して投稿できる一次情報ベースの案を蓄積できた。",
    input: "当日のデイリー、反応ログ、DiginoteAI更新、作業中の気づき。",
    humanCheck: "最終的な言い回し、絵文字、投稿タイミングは本人が決めると伸びる型を学習しやすい。",
    fit: "SNSをAI任せにしすぎず、自分のトーンを育てたい人。",
    caution: "AIの完成文をそのまま出すより、本人の熱量を足した方が反応を取りやすい。",
    link: "https://note.com/locany",
    linkLabel: "発信運用の考え方を見る",
    tags: ["Threads", "投稿案", "トンマナ"]
  },
  {
    id: "search-console-check",
    title: "Search Consoleの詰まりを確認する",
    agent: "Codex",
    category: "分析",
    purpose: "サイトマップ、URL検査、検索パフォーマンスを見て、次の一手を決める。",
    result: "サイト側の公開状態とSearch Console側の認識待ちを分けて判断できた。",
    input: "対象サイトURL、Search Console画面、サイトマップURL、公開済み記事。",
    humanCheck: "インデックス登録リクエストの上限や重要ページの優先順位は人間と相談するとよい。",
    fit: "公開した記事が検索に見つからない原因を切り分けたい人。",
    caution: "すぐに検索流入が出ない時でも、サイト側の問題とは限らない。",
    link: "https://ai-workroom-catalog.pages.dev/",
    linkLabel: "実験サイトを見る",
    tags: ["Search Console", "SEO", "サイトマップ"]
  },
  {
    id: "theme-route-improvement",
    title: "WordPressテーマに記事回遊導線を追加する",
    agent: "Codex",
    category: "Web制作",
    purpose: "TOPページから記事一覧、カテゴリ、新着記事へ自然に進める導線を作る。",
    result: "テーマ側で新着記事やカテゴリ導線を表示できる設計に変更できた。",
    input: "テーマファイル、現在のTOPページ、記事カテゴリ、表示/非表示の要件。",
    humanCheck: "どのカテゴリを見せるか、売りたいサービスへどう流すかは運営方針に合わせる。",
    fit: "WordPressサイトの回遊率を上げたい人、記事から商品導線へつなげたい人。",
    caution: "テーマ更新後は、実サイトへZIPアップロードして表示確認が必要。",
    link: "https://acs-developer.com/",
    linkLabel: "サイト改善相談",
    tags: ["テーマ改修", "回遊", "内部リンク"]
  },
  {
    id: "youtube-script-slides",
    title: "YouTube台本とスライド構成を作る",
    agent: "Codex",
    category: "YouTube",
    purpose: "noteやサイト運用の内容を、YouTube動画の構成と台本に変換する。",
    result: "動画の導入、章立て、話す内容、画面に出すスライド案まで整理できた。",
    input: "元記事、訴求したい商品、動画の目的、想定視聴者。",
    humanCheck: "話すテンポ、尺、声に出した時の自然さは収録前に人間が調整するとよい。",
    fit: "記事やnoteを動画導線へ展開したい人。",
    caution: "想定尺に対して台本が短くなりやすいので、収録尺ベースで確認する。",
    link: "https://www.youtube.com/",
    linkLabel: "YouTubeで活用",
    tags: ["台本", "スライド", "動画導線"]
  },
  {
    id: "cloudflare-static-mvp",
    title: "Cloudflare Pages向けの静的MVPを作る",
    agent: "Codex",
    category: "Web制作",
    purpose: "サーバーを持たず、無料枠で公開できる静的サイトを作る。",
    result: "HTML/CSS/JavaScriptだけで、検索・カテゴリ・詳細表示のあるMVPを作成できた。",
    input: "サイト名、コンセプト、掲載したい初期データ、将来の拡張方針。",
    humanCheck: "ドメイン接続、Cloudflare Pagesのプロジェクト作成、公開前のブランド確認は人間が行う。",
    fit: "まず軽く検証したい新規サイト、サテライトサイト、事例集。",
    caution: "会員登録や投稿機能を付ける場合は、後からSupabaseなどのDBが必要になる。",
    link: "https://pages.cloudflare.com/",
    linkLabel: "Cloudflare Pages",
    tags: ["静的サイト", "MVP", "Cloudflare"]
  },
  {
    id: "ai-agent-workroom-dark-gallery-ui",
    title: "AI Agent Workroomの黒背景ギャラリーUIを公開する",
    agent: "Codex",
    category: "Web制作",
    purpose: "AIでできた制作物を寝る前にも眺めやすい黒背景の作品ギャラリーとして見せ、詳細ページをSEO資産として増やせる形にする。",
    result: "黒背景、青い発光、画像付き作品カード、詳細ページ、いいね表示、人気順・おすすめ順・将来のピックアップ枠まで実装してCloudflare Pagesへ公開できた。",
    input: "サイトの目的、参考画像、既存の静的サイト一式、GitHubとCloudflare Pagesの公開環境。",
    humanCheck: "夜に見ても眩しくない暗さ、作品カードの見せ方、販売導線へつなげる文言は人間が判断するとよい。",
    fit: "AIで作った制作物をカード化し、サービス販売や制作依頼につながるポートフォリオにしたい人。",
    caution: "いいね数は現時点ではローカル保存の試作。全体集計には将来的にDBが必要。",
    link: "https://acs-developer.com/",
    linkLabel: "サイト制作相談を見る",
    tags: ["Dark UI", "詳細ページ", "制作実績"]
  }
];

const WORK_CASE_META = {
  "wordpress-daily-publish": {
    summary: "反応ログとPDCAを見て、その日に書くべき記事を3本選び、WordPressへ公開まで進めた運用事例。",
    likes: 128,
    timeAgo: "今日",
    author: "@acs_operator",
    role: "WordPress運用 / AI秘書",
    metricLabel: "公開本数",
    before: "0本",
    after: "3本",
    featured: true
  },
  "wordpress-image-insert": {
    summary: "生成済みのアイキャッチと挿絵を、複数の記事へ対応順に挿入した制作補助事例。",
    likes: 96,
    timeAgo: "今日",
    author: "@acs_operator",
    role: "WordPress運用 / 画像反映",
    metricLabel: "画像反映",
    before: "未挿入",
    after: "12枚",
    featured: true
  },
  "obsidian-secretary-review": {
    summary: "Obsidian Vaultを読み、朝レビュー・夜まとめ・タスク判断までつなげたAI秘書の実践ログ。",
    likes: 211,
    timeAgo: "1日前",
    author: "@locany_workroom",
    role: "AI秘書 / Obsidian運用",
    metricLabel: "整理範囲",
    before: "散在",
    after: "日次化",
    featured: true
  },
  "note-publish-blog": {
    summary: "Obsidianの下書きをnoteへ移し、タグ、マガジン、公開設定まで整えた発信運用事例。",
    likes: 84,
    timeAgo: "1日前",
    author: "@locany_note",
    role: "note運用 / 編集",
    metricLabel: "公開準備",
    before: "下書き",
    after: "公開"
  },
  "diginote-ai-update": {
    summary: "AI企業リサーチから一次情報を確認し、DiginoteAI向けの記事更新へつなげたニュース運用事例。",
    likes: 172,
    timeAgo: "2日前",
    author: "@diginoteai",
    role: "AIニュース / リサーチ",
    metricLabel: "更新",
    before: "調査",
    after: "記事化",
    recommended: true
  },
  "threads-draft-stock": {
    summary: "日々の会話や作業ログから、手動リライト前提のThreads投稿案をストックする運用設計。",
    likes: 143,
    timeAgo: "2日前",
    author: "@nanachan0410",
    role: "SNS運用 / トンマナ学習",
    metricLabel: "投稿案",
    before: "0案",
    after: "30案"
  },
  "search-console-check": {
    summary: "Search Consoleの表示、クリック、CTR、インデックス状況を確認し、次の改善候補を切り分けた分析ログ。",
    likes: 75,
    timeAgo: "3日前",
    author: "@seo_workroom",
    role: "SEO分析 / Search Console",
    metricLabel: "確認項目",
    before: "曖昧",
    after: "4項目"
  },
  "theme-route-improvement": {
    summary: "TOPページから記事一覧、カテゴリ、新着記事へ回すためのWordPressテーマ導線を改善した制作事例。",
    likes: 189,
    timeAgo: "3日前",
    author: "@acs_developer",
    role: "WordPressテーマ / 回遊設計",
    metricLabel: "導線",
    before: "検索流入のみ",
    after: "TOP回遊",
    recommended: true
  },
  "youtube-script-slides": {
    summary: "noteやサイト運用の内容を、YouTubeの台本とスライド構成へ展開した動画制作準備の事例。",
    likes: 64,
    timeAgo: "4日前",
    author: "@diginote_video",
    role: "YouTube / 台本設計",
    metricLabel: "制作状態",
    before: "記事",
    after: "収録前"
  },
  "cloudflare-static-mvp": {
    summary: "サーバーを持たず、Cloudflare Pagesで検索・カテゴリ・詳細表示つきの静的MVPを公開した事例。",
    likes: 156,
    timeAgo: "4日前",
    author: "@workroom_build",
    role: "静的サイト / Cloudflare",
    metricLabel: "公開費用",
    before: "未公開",
    after: "無料枠",
    recommended: true
  },
  "ai-agent-workroom-dark-gallery-ui": {
    summary: "AI Agent Workroom自体を、制作実績として見せられる黒背景の作品ギャラリー型サイトへ再設計した事例。",
    likes: 242,
    timeAgo: "今夜",
    author: "@workroom_build",
    role: "Web制作 / UIデザイン",
    metricLabel: "サイト状態",
    before: "普通",
    after: "作品化",
    featured: true,
    recommended: true
  }
};

window.AGENT_WORKS_CASES = window.AGENT_WORKS_CASES.map((item, index) => {
  const meta = WORK_CASE_META[item.id] || {};
  return {
    ...item,
    ...meta,
    image: `./assets/work-previews/${item.id}.png`,
    imageAlt: `${item.title} の制作物プレビュー`,
    detailUrl: `./works/${item.id}/`,
    galleryCount: meta.galleryCount || 1,
    likes: meta.likes || 24 + index * 7,
    timeAgo: meta.timeAgo || "公開中",
    author: meta.author || "@ai_agent_workroom",
    role: meta.role || `${item.agent} / ${item.category}`,
    metricLabel: meta.metricLabel || "制作結果",
    before: meta.before || "依頼前",
    after: meta.after || "完了",
    summary: meta.summary || item.result
  };
});
